### ISSUE TITLE
Update README to briefly explain the MASP project

### ISSUE THREAD

**Issue by cwgoes** [anoma/masp#1]
Let's just add a quick README explaining what the MASP is and linking to the spec.

**Comment by cwgoes** [comment]
We can move the spec into this repository, that will probably be clearer.

**Comment by awasunyin** [comment]
@joebebel note that you can find the MASP visual assets (logo, etc) in different formats [on this folder](https://drive.google.com/drive/u/1/folders/1rRvQ-TLgC7FYuX5r646JTmduy9l27_Kp). Feel free to use them on the README if you see fit.
