### ISSUE TITLE
Unify specifications

### ISSUE THREAD

**Issue by joebebel** [anoma/masp#17]
Currently, the specifications for MASP are divided among several places:

1. The original Zcash Sapling specification
2. The cryptographic MASP specification at https://github.com/anoma/masp/blob/main/docs/multi-asset-shielded-pool.pdf
3. The MASP transaction format and validity predicate in the Anoma specifications at https://spec.anoma.network/master/architecture/namada/masp.html

This makes it a bit difficult to review the entire protocol. It may be useful to merge everything into a single comprehensive spec.

**Comment by cwgoes** [comment]
Agreed to add the convert circuit to the MASP circuit, and leave it at that.
